export type BlockDocSetting = {
  label: string;
  description: string;
  notes?: string;
};

export type BlockDoc = {
  name: string;
  group: string;
  plan?: string;
  summary: string;
  bestUsedFor: string[];
  features: string[];
  settings: BlockDocSetting[];
  tips: string[];
  notes?: string[];
};

export const blockDocs: BlockDoc[] = [
  {
    name: 'Hero Section',
    group: 'Page Structure',
    summary: 'Creates a prominent introductory section with one or more configurable hero cards.',
    bestUsedFor: [
      'Top-of-page introductions',
      'Landing page headlines',
      'Important offers or announcements',
      'Rotating homepage hero messages',
    ],
    features: [
      'Build one hero card or a rotating set of hero cards.',
      'Configure title, subtitle, CTA, foreground image, and background per card.',
      'Use image, video, gradient, or animated backgrounds.',
      'Control card transitions, timing, and pause-on-hover behavior.',
      'Tune hero height separately for desktop, tablet, and mobile.',
    ],
    settings: [
      { label: 'Hero cards', description: 'Adds, duplicates, deletes, reorders, and selects individual hero cards.' },
      { label: 'Card transition', description: 'Controls how multiple hero cards rotate.', notes: 'Available transition types include Fade, Slide, and None, with interval and pause-on-hover controls.' },
      { label: 'Title', description: 'Shows, hides, edits, and aligns the title for the selected card.' },
      { label: 'Subtitle', description: 'Shows, hides, edits, and aligns the supporting text for the selected card.' },
      { label: 'CTA button', description: 'Shows, hides, edits, links, and aligns the button for the selected card.' },
      { label: 'Foreground image', description: 'Shows or hides an image beside the text for the selected card.', notes: 'The image can be placed on the left or right.' },
      { label: 'Background type', description: 'Chooses the selected card background.', notes: 'Available choices include Image, Video, Gradient, and Animation.' },
      { label: 'Background image', description: 'Chooses the image used behind the selected card content.' },
      { label: 'Background video', description: 'Adds a Pexels or external video background for the selected card.' },
      { label: 'Gradient', description: 'Controls the gradient colors and angle for the selected card.' },
      { label: 'Animation', description: 'Chooses an animated background preset for the selected card.' },
      { label: 'Overlay', description: 'Sets overlay color and opacity for image, video, and animated backgrounds.' },
      { label: 'Height mode', description: 'Controls whether the hero fits content, fills the screen, or uses a manual height.' },
      { label: 'Device heights', description: 'Sets desktop, tablet, and mobile hero height behavior independently.' },
      { label: 'Reveal next section', description: 'Lets full-screen heroes reveal part of the following section.' },
      { label: 'Custom CSS', description: 'Adds advanced custom styling when available for the account.' },
    ],
    tips: [
      'Keep each hero card focused on one message and one main action.',
      'Use transitions sparingly so the first card still works if a visitor never waits for the next card.',
      'Check desktop, tablet, and mobile height settings after changing foreground images or full-screen behavior.',
      'If using a background image, video, or animation, use overlay controls to keep text readable.',
    ],
  },
  {
    name: 'Rich Text Paragraph',
    group: 'Page Structure',
    summary: 'Adds editable formatted text to a page.',
    bestUsedFor: [
      'Body copy',
      'Simple article-style sections',
      'Explanations that need headings, lists, or inline formatting',
    ],
    features: [
      'Write and edit rich text directly in the builder.',
      'Use common formatting such as headings, bold, italic, and lists.',
      'Add links inside the text.',
    ],
    settings: [
      { label: 'Rich text content', description: 'Controls the text shown in the block.' },
      { label: 'Formatting toolbar', description: 'Provides visible text-formatting controls while editing.', notes: 'Formatting options appear in the editor.' },
    ],
    tips: [
      'Break long content into short paragraphs for easier scanning.',
      'Use headings to organize longer text sections.',
      'Use descriptive link text so visitors know what will open.',
    ],
  },
  {
    name: 'Image Section',
    group: 'Media',
    summary: 'Adds a large image to the page.',
    bestUsedFor: [
      'Featured photos',
      'Portfolio images',
      'Visual breaks between text-heavy sections',
    ],
    features: [
      'Upload or replace an image.',
      'Displays the image as a wide featured visual.',
      'Supports image settings provided by the builder image picker.',
    ],
    settings: [
      { label: 'Image', description: 'Chooses the image shown in the block.' },
      { label: 'Image settings', description: 'Adjusts available image details in the image picker.', notes: 'Add meaningful alt text when that option is available.' },
    ],
    tips: [
      'Use high-quality images that are relevant to nearby content.',
      'Avoid images with important text inside the image itself.',
      'Add alt text when the image picker offers it.',
    ],
  },
  {
    name: 'Services Grid',
    group: 'Content Lists',
    summary: 'Shows a group of services in a grid.',
    bestUsedFor: [
      'Service overviews',
      'What you offer sections',
      'Short descriptions of business capabilities',
    ],
    features: [
      'Add a section title and subtitle.',
      'Add and remove service cards directly on the page.',
      'Each service includes a title and description.',
      'Optionally show or hide the bottom CTA link.',
    ],
    settings: [
      { label: 'Title', description: 'Sets the heading for the services section.' },
      { label: 'Subtitle', description: 'Adds supporting text above the service cards.' },
      { label: 'Service items', description: 'Controls the services shown in the grid.', notes: 'Each item includes a service name and description and can be added or removed inline.' },
      { label: 'Show bottom link', description: 'Shows or hides the CTA link below the services.' },
      { label: 'Bottom link label', description: 'Sets the text for the CTA link.', notes: 'Use a generic action such as Learn More, View Services, or Book Now.' },
      { label: 'Bottom link URL', description: 'Sets where the CTA link goes.' },
    ],
    tips: [
      'Use short service names so the grid stays easy to scan.',
      'Keep each description to one or two sentences.',
      'Put the most important services first.',
    ],
  },
  {
    name: 'Features / Why Us',
    group: 'Content Lists',
    summary: 'Highlights reasons to choose your business or organization.',
    bestUsedFor: [
      'Why choose us sections',
      'Benefit lists',
      'Quick trust-building points',
    ],
    features: [
      'Add a section title.',
      'Add and remove repeated feature statements.',
      'Presents features as a scannable list.',
    ],
    settings: [
      { label: 'Title', description: 'Sets the heading for the feature list.' },
      { label: 'Feature items', description: 'Controls the list of benefits or reasons shown in the block.', notes: 'Items can be added or removed directly while editing the page.' },
    ],
    tips: [
      'Write each feature as a clear benefit.',
      'Use parallel wording for a polished list.',
      'Avoid making the list too long.',
    ],
  },
  {
    name: 'About (Image + Text)',
    group: 'Page Structure',
    summary: 'Combines an image with descriptive text and optional bullet points.',
    bestUsedFor: [
      'About sections',
      'Founder or company introductions',
      'Explaining a process with supporting imagery',
    ],
    features: [
      'Add a heading and descriptive text.',
      'Display an image alongside the content.',
      'Add and remove bullet-style supporting points.',
      'Choose the image side and image shape.',
      'The empty upload area reflects the selected image aspect ratio.',
    ],
    settings: [
      { label: 'Title', description: 'Sets the heading for the section.' },
      { label: 'Description', description: 'Adds the main paragraph text.' },
      { label: 'Image', description: 'Chooses the image displayed with the text.' },
      { label: 'Image position', description: 'Places the image on the left or right side of the section.' },
      { label: 'Items', description: 'Adds, removes, and edits short supporting points.' },
      { label: 'Image aspect', description: 'Changes the image shape.', notes: 'Available shapes include Landscape, Square, and Tall. The upload placeholder updates to match this selection even before an image is chosen.' },
      { label: 'Section background color', description: 'Sets the background color for the section.' },
    ],
    tips: [
      'Use an image that helps explain the text rather than a generic decoration.',
      'Keep the description focused on one main idea.',
      'Use the bullet points for quick proof points or highlights.',
    ],
  },
  {
    name: 'Testimonials',
    group: 'Trust',
    summary: 'Shows customer or client quotes.',
    bestUsedFor: [
      'Social proof',
      'Customer review sections',
      'Highlighting client feedback',
    ],
    features: [
      'Add a title and subtitle.',
      'Add and remove testimonial cards.',
      'Each testimonial can include a name, role, quote, and rating.',
      'Choose between card grid, horizontal scrolling, and single-focus layouts.',
      'Limit how many cards are shown before a Show More button.',
      'Enable auto-scroll, infinite scrolling, or looping scroll behavior for scrolling layouts.',
    ],
    settings: [
      { label: 'Title', description: 'Sets the heading for the testimonial section.' },
      { label: 'Subtitle', description: 'Adds supporting text above the testimonials.' },
      { label: 'Testimonials', description: 'Controls the quotes shown in the block.', notes: 'Visible details include name, role, quote, and rating. Cards can be added or removed inline.' },
      { label: 'Layout', description: 'Changes how testimonials are displayed.', notes: 'Available layouts include Cards, Horizontal Scroll, and Single Focus.' },
      { label: 'Show More button', description: 'Shows or hides a button for revealing additional testimonial cards.' },
      { label: 'Visible card count', description: 'Limits the number of testimonial cards shown before Show More appears.' },
      { label: 'Auto-scroll', description: 'Automatically scrolls testimonials when the scrolling layout is used.' },
      { label: 'Scroll interval', description: 'Controls the timing between automatic testimonial scrolls.' },
      { label: 'Infinite scrolling', description: 'Lets the testimonial row continue instead of stopping at the last card.' },
      { label: 'Loop auto-scroll', description: 'Loops the automatic scrolling behavior rather than only moving back and forth.' },
    ],
    tips: [
      'Use real, permission-approved quotes.',
      'Keep quotes concise for readability.',
      'Choose Single Focus when one quote is especially important.',
    ],
  },
  {
    name: 'Stats / Numbers',
    group: 'Trust',
    summary: 'Displays important numbers or metrics.',
    bestUsedFor: [
      'Performance highlights',
      'Experience or scale indicators',
      'Quick credibility sections',
    ],
    features: [
      'Add an optional heading.',
      'Add and remove repeated number-and-label items.',
      'Choose between banner and card-style layouts.',
    ],
    settings: [
      { label: 'Title', description: 'Sets the optional heading for the statistics.' },
      { label: 'Stat items', description: 'Controls each number and label shown.', notes: 'Stat cards can be added or removed directly while editing.' },
      { label: 'Layout', description: 'Changes the presentation style.', notes: 'Available layouts include Horizontal Banner and Statistic Cards.' },
      { label: 'Section background color', description: 'Sets the background color for the statistics section.' },
    ],
    tips: [
      'Use numbers that visitors can understand quickly.',
      'Pair every number with a clear label.',
      'Avoid using too many stats in one block.',
    ],
  },
  {
    name: 'Image Gallery',
    group: 'Media',
    summary: 'Displays a collection of images.',
    bestUsedFor: [
      'Portfolios',
      'Venue or product galleries',
      'Before-and-after or project collections',
    ],
    features: [
      'Add a title and subtitle.',
      'Upload multiple images.',
      'Choose the number of columns.',
      'Enable expanded image viewing.',
      'Optionally show a See More button or auto-scroll images.',
    ],
    settings: [
      { label: 'Title', description: 'Sets the gallery heading.' },
      { label: 'Subtitle', description: 'Adds supporting text above the gallery.' },
      { label: 'Images', description: 'Controls the images shown in the gallery.' },
      { label: 'Columns', description: 'Controls how many image columns are used.', notes: 'Available options are 2, 3, and 4 columns.' },
      { label: 'Expanded Image', description: 'Controls the larger image view.' },
      { label: 'Show navigation buttons', description: 'Shows previous and next buttons in the expanded image view.' },
      { label: 'Show thumbnail strip', description: 'Shows image thumbnails in the expanded image view.' },
      { label: 'Show See More button', description: 'Adds a button after the gallery.', notes: 'Button text and link can be customized on the page.' },
      { label: 'Auto-scroll images', description: 'Automatically scrolls the gallery images.' },
      { label: 'Rows', description: 'Controls the number of rows used when auto-scroll is enabled.', notes: 'Available options are 1 to 4 rows.' },
    ],
    tips: [
      'Use images with a consistent style for a cleaner gallery.',
      'Use the expanded image options when visitors need to inspect photos closely.',
      'Avoid adding too many images if the page needs to load quickly.',
    ],
  },
  {
    name: 'Contact Info',
    group: 'Contact',
    summary: 'Shows configurable contact cards and social links.',
    bestUsedFor: [
      'Contact pages',
      'Footer-adjacent contact sections',
      'Business location and hours information',
    ],
    features: [
      'Show, hide, and edit the section title and subtitle.',
      'Add, remove, and reorder contact cards.',
      'Choose icons for phone, email, address, hours, website, message, mobile, directions, support, business, and more.',
      'Set each card label, value, and link behavior.',
      'Add, remove, and reorder social media icons.',
      'Choose card columns, social heading visibility, background color, and icon colors.',
    ],
    settings: [
      { label: 'Contact cards', description: 'Controls the contact cards shown in the block.', notes: 'Cards start collapsed in the settings menu so they are easier to reorder.' },
      { label: 'Add contact card', description: 'Adds another contact card with its own icon, label, value, and link behavior.' },
      { label: 'Reorder contact cards', description: 'Moves cards by dragging the handle in the block or settings menu.' },
      { label: 'Card icon', description: 'Chooses the icon shown on a contact card.' },
      { label: 'Card label', description: 'Sets the short label shown above the card value.' },
      { label: 'Card value', description: 'Sets the main contact text shown on the card.' },
      { label: 'Link behavior', description: 'Controls what happens when a visitor clicks a contact card.', notes: 'Cards can use automatic phone, email, map, website, or custom URL behavior depending on the card type.' },
      { label: 'Social icons', description: 'Controls the social media icons shown below the contact cards.', notes: 'Supported options include common social platforms and custom links.' },
      { label: 'Add social icon', description: 'Adds another social platform icon.' },
      { label: 'Reorder social icons', description: 'Moves social icons by dragging the handle in the block or settings menu.' },
      { label: 'Social platform', description: 'Chooses the social icon and matching label.' },
      { label: 'Social URL', description: 'Sets the social link destination.', notes: 'In edit mode, social icons without URLs show a warning so unfinished links are easy to find.' },
      { label: 'Card columns', description: 'Chooses whether contact cards display in one or two columns.' },
      { label: 'Show title', description: 'Shows or hides the section title.' },
      { label: 'Title text', description: 'Sets the section title.' },
      { label: 'Show subtitle', description: 'Shows or hides the subtitle.' },
      { label: 'Subtitle text', description: 'Sets the section subtitle.' },
      { label: 'Show social heading', description: 'Shows or hides the heading above social icons.' },
      { label: 'Social heading text', description: 'Sets the social heading.' },
      { label: 'Section background color', description: 'Sets the contact section background.' },
      { label: 'Contact card icon color', description: 'Sets the icon color used inside contact cards.' },
      { label: 'Social icon color', description: 'Sets the color used for social icons.' },
      { label: 'Custom CSS', description: 'Adds advanced custom styling when available for the account.' },
    ],
    tips: [
      'Keep the most important contact methods first.',
      'Use consistent icon colors unless a brand color is important.',
      'Remove social icons that are not active, or leave unfinished URLs visible only while editing until they are ready.',
      'Pair this block with a Contact Form when you want visitors to send messages directly.',
    ],
  },
  {
    name: 'FAQ Accordion',
    group: 'Content Lists',
    summary: 'Adds a list of expandable questions and answers.',
    bestUsedFor: [
      'Common questions',
      'Service or product clarifications',
      'Reducing repeated support questions',
    ],
    features: [
      'Add a title and subtitle.',
      'Add multiple questions and answers.',
      'Visitors can expand answers as needed.',
    ],
    settings: [
      { label: 'Title', description: 'Sets the FAQ section heading.' },
      { label: 'Subtitle', description: 'Adds supporting text above the questions.' },
      { label: 'Questions and answers', description: 'Controls each FAQ item.' },
    ],
    tips: [
      'Write questions in the same words visitors would use.',
      'Keep answers direct and practical.',
      'Put the most common questions near the top.',
    ],
  },
  {
    name: 'Call to Action',
    group: 'Page Structure',
    summary: 'Adds a focused prompt that encourages visitors to take action.',
    bestUsedFor: [
      'End-of-page conversion sections',
      'Promoting booking, contact, signup, or shopping actions',
      'Breaking up long pages with a clear next step',
    ],
    features: [
      'Add a title and subtitle.',
      'Add a button with a link.',
      'Optionally show a decorative background pattern.',
    ],
    settings: [
      { label: 'Title', description: 'Sets the main call-to-action text.' },
      { label: 'Subtitle', description: 'Adds supporting text.' },
      { label: 'Button', description: 'Sets the button label and destination.' },
      { label: 'Show pattern', description: 'Shows or hides the decorative background pattern.' },
    ],
    tips: [
      'Use action-oriented button text.',
      'Make the action match the visitor’s next natural step.',
      'Avoid placing too many different actions in one call-to-action section.',
    ],
  },
  {
    name: 'Booking / Appointments',
    group: 'Commerce and Scheduling',
    summary: 'Adds an online booking flow to the page.',
    bestUsedFor: [
      'Appointment booking',
      'Service scheduling',
      'Businesses that need visitors to choose a service and time',
    ],
    features: [
      'Displays a booking flow on the live site.',
      'Connects to services, categories, hours, and booking settings managed separately.',
      'Provides a Manage Services action in edit mode.',
    ],
    settings: [
      { label: 'Manage Services', description: 'Opens the booking management area for services, hours, and booking setup.' },
      { label: 'Categories', description: 'Organizes bookable services.' },
      { label: 'Services', description: 'Controls the services visitors can book.' },
      { label: 'Hours', description: 'Controls appointment availability.' },
      { label: 'Settings', description: 'Controls booking setup options shown in the booking manager.' },
    ],
    tips: [
      'Set up services and hours before publishing a booking page.',
      'Use clear service names and descriptions.',
      'Review the booking flow after changing availability.',
    ],
    notes: [
      'This block needs a saved site before it can be fully managed.',
    ],
  },
  {
    name: 'Product Catalog',
    group: 'Commerce and Scheduling',
    summary: 'Displays products from your store on a page.',
    bestUsedFor: [
      'Shop pages',
      'Featured product sections',
      'Category-specific product displays',
    ],
    features: [
      'Displays products managed separately.',
      'Filter products by category or subcategory.',
      'Show only featured products.',
      'Add an optional view-more button.',
      'Choose from several product layouts.',
    ],
    settings: [
      { label: 'Show category', description: 'Limits the block to one product category.', notes: 'All categories can be shown if no category is selected.' },
      { label: 'Show subcategory', description: 'Limits the block to a subcategory when a category is selected.' },
      { label: 'Featured products only', description: 'Shows only products marked as featured.' },
      { label: 'Show view more button', description: 'Adds a link button after the products.' },
      { label: 'Button label', description: 'Sets the text for the view-more button.' },
      { label: 'Button link', description: 'Sets where the view-more button goes.' },
      { label: 'Layout', description: 'Changes how products are arranged.', notes: 'Available layouts include Grid, Scrolling Row, Grid + Category Sidebar, and List View.' },
      { label: 'Manage Products', description: 'Opens the product management area.' },
    ],
    tips: [
      'Use featured products for homepage highlights.',
      'Use category filters for focused shop pages.',
      'Make sure products are active and have clear images before publishing.',
    ],
    notes: [
      'Products are managed separately from the page builder.',
    ],
  },
  {
    name: 'Contact Form',
    group: 'Contact',
    summary: 'Adds a message form visitors can submit.',
    bestUsedFor: [
      'Contact pages',
      'Lead capture',
      'General inquiries',
    ],
    features: [
      'Shows fields for name, email, phone, and message.',
      'Customize the section title and description.',
      'Customize the submit button and success message.',
      'Provides a link to manage messages in the inbox.',
    ],
    settings: [
      { label: 'Title', description: 'Sets the form heading.' },
      { label: 'Description', description: 'Adds supporting text above the form.' },
      { label: 'Submit button text', description: 'Sets the label shown on the submit button.' },
      { label: 'Success message', description: 'Sets the message visitors see after submitting.' },
      { label: 'Manage Inbox', description: 'Opens the area where messages can be reviewed.' },
    ],
    tips: [
      'Keep the description short and welcoming.',
      'Use a submit label that matches the action, such as Send Message or Request Info.',
      'Check the inbox settings before relying on the form for live inquiries.',
    ],
  },
  {
    name: 'Estimate / Quote Form',
    group: 'Contact',
    summary: 'Adds a customizable quote or estimate request form.',
    bestUsedFor: [
      'Service estimates',
      'Project inquiries',
      'Quote requests with optional live pricing',
    ],
    features: [
      'Choose between Inquiry Form and Estimate Calculator layouts.',
      'Add custom intake fields.',
      'Show or hide contact fields.',
      'Configure optional live pricing for calculator forms.',
      'Customize submit text and success message.',
      'Uses inline form configuration inside the block instead of a duplicate side settings menu.',
    ],
    settings: [
      { label: 'Layout', description: 'Switches between Inquiry Form and Estimate Calculator.' },
      { label: 'Form Title', description: 'Sets the form heading.' },
      { label: 'Description text', description: 'Adds supporting text above the fields.' },
      { label: 'Submit button text', description: 'Sets the button label.' },
      { label: 'Success message', description: 'Sets the message visitors see after submitting.' },
      { label: 'Custom Fields', description: 'Adds, removes, reorders, and edits custom questions.', notes: 'Available field types include Dropdown, Number, Text, Textarea, and Checkbox.' },
      { label: 'Options', description: 'Adds choices for dropdown fields.' },
      { label: 'Min and Max', description: 'Sets a visible range for number fields.' },
      { label: 'Unit', description: 'Adds a unit label to number fields.' },
      { label: 'Required', description: 'Marks a field as required.' },
      { label: 'Contact Fields', description: 'Shows or hides standard contact fields.', notes: 'Available contact fields include Full Name, Email, Phone, Address, Preferred Date, and Additional Notes.' },
      { label: 'Pricing', description: 'Turns live pricing on or off for calculator forms.' },
      { label: 'Base Price', description: 'Sets the starting amount used by the calculator.' },
      { label: 'Currency', description: 'Sets the currency shown for estimates.' },
      { label: 'Range Spread', description: 'Controls how wide the estimate range appears.' },
      { label: 'Disclaimer Text', description: 'Adds explanatory text below the estimate.' },
      { label: 'Manage Inbox', description: 'Opens the area where quote and estimate submissions can be reviewed.' },
    ],
    tips: [
      'Ask only for information you truly need to prepare a quote.',
      'Use dropdowns for common choices and text areas for open-ended details.',
      'Review the public form after changing pricing settings.',
    ],
  },
  {
    name: 'Logo Cloud / Partners',
    group: 'Trust',
    summary: 'Displays partner, client, or sponsor logos.',
    bestUsedFor: [
      'Partner sections',
      'Client logo rows',
      'Trust-building social proof',
    ],
    features: [
      'Add a section title.',
      'Show logos in multiple layouts.',
      'Supports inline, grid, and scrolling logo presentations.',
    ],
    settings: [
      { label: 'Title', description: 'Sets the heading above the logos.' },
      { label: 'Logos', description: 'Controls the logos shown in the block.' },
      { label: 'Layout', description: 'Changes the logo presentation.', notes: 'Available layouts include Inline Row, Logo Grid, and Scrolling Marquee.' },
    ],
    tips: [
      'Use clean logo files with consistent sizing.',
      'Avoid showing too many logos if the section becomes visually noisy.',
      'Use the scrolling layout when you have many logos to display.',
    ],
  },
  {
    name: 'Pricing Table',
    group: 'Commerce and Scheduling',
    summary: 'Shows pricing tiers or package options.',
    bestUsedFor: [
      'Service packages',
      'Membership tiers',
      'Plan comparisons',
    ],
    features: [
      'Add a title and subtitle.',
      'Add multiple pricing tiers.',
      'Each tier can include price, period, description, and feature list.',
      'Highlight a tier.',
      'Choose between pricing layouts.',
    ],
    settings: [
      { label: 'Title', description: 'Sets the pricing section heading.' },
      { label: 'Subtitle', description: 'Adds supporting text above the plans.' },
      { label: 'Pricing tiers', description: 'Controls each plan or package shown.' },
      { label: 'Highlighted tier', description: 'Emphasizes one plan visually.' },
      { label: 'Layout', description: 'Changes how pricing is displayed.', notes: 'Available layouts include Pricing Cards, Comparison Table, and Simple List.' },
    ],
    tips: [
      'Keep plan names short and easy to compare.',
      'Highlight the plan you most want visitors to choose.',
      'Use feature lists for differences visitors care about.',
    ],
  },
  {
    name: 'Team Members',
    group: 'Trust',
    summary: 'Shows people on your team.',
    bestUsedFor: [
      'About pages',
      'Staff introductions',
      'Professional profiles',
    ],
    features: [
      'Add a section title.',
      'Add multiple team members.',
      'Each member can include a name, role, and bio.',
      'Choose between team layouts.',
    ],
    settings: [
      { label: 'Title', description: 'Sets the team section heading.' },
      { label: 'Team members', description: 'Controls the people shown in the block.' },
      { label: 'Layout', description: 'Changes the team presentation.', notes: 'Available layouts include Simple Grid, Detailed Cards, and Minimalist.' },
    ],
    tips: [
      'Use consistent bio length for each person.',
      'Keep roles clear and visitor-friendly.',
      'Use the detailed layout when bios are important.',
    ],
  },
  {
    name: 'Google Map',
    group: 'Contact',
    summary: 'Embeds a map for a location.',
    bestUsedFor: [
      'Contact pages',
      'Store or office location sections',
      'Helping visitors find a physical place',
    ],
    features: [
      'Add a title.',
      'Enter an address or landmark.',
      'Shows an embedded map for the location.',
    ],
    settings: [
      { label: 'Title', description: 'Sets the map section heading.' },
      { label: 'Address or landmark', description: 'Sets the location shown on the map.' },
    ],
    tips: [
      'Use the full address when possible.',
      'Pair the map with the Contact Info block for phone, email, and hours.',
    ],
  },
  {
    name: 'Blog / News',
    group: 'Content Feeds',
    summary: 'Displays published blog posts or news articles.',
    bestUsedFor: [
      'Blog pages',
      'News sections',
      'Recent updates on a homepage',
    ],
    features: [
      'Add a section title and subtitle.',
      'Choose Grid, List, or Magazine display.',
      'Show or hide author, date, tags, and excerpt.',
      'Control how many posts appear.',
      'Open the blog post manager from the block.',
    ],
    settings: [
      { label: 'Section Title', description: 'Sets the blog section heading.' },
      { label: 'Subtitle', description: 'Adds supporting text above the posts.' },
      { label: 'List Style', description: 'Changes the blog layout.', notes: 'Available styles include Grid, List, and Magazine.' },
      { label: 'Display Options', description: 'Shows or hides post details.', notes: 'Available details include Author, Date, Tags, and Excerpt.' },
      { label: 'Posts Per Page', description: 'Controls how many posts are shown.', notes: 'Available counts include 3, 6, 9, 12, and 15.' },
      { label: 'Manage Blog Posts', description: 'Opens the blog post manager.' },
    ],
    tips: [
      'Use Magazine when you want one post to feel featured.',
      'Use List for text-heavy updates.',
      'Publish posts before expecting them to appear on the live site.',
    ],
    notes: [
      'Blog posts are managed separately from the page builder.',
    ],
  },
  {
    name: 'Menu',
    group: 'Content Feeds',
    summary: 'Displays a restaurant or food menu.',
    bestUsedFor: [
      'Restaurant menu pages',
      'Cafe or bar menus',
      'Food and drink highlights',
    ],
    features: [
      'Use structured menu items or a PDF/image menu.',
      'Preview menu sections while designing.',
      'Choose menu layouts and category styles.',
      'Show or hide prices, descriptions, tabs, photos, and menu item icons.',
      'Support item detail popups with customizable photo and caption options.',
      'Show a menu icon legend with built-in and custom icons.',
      'Open the menu manager from the block.',
    ],
    settings: [
      { label: 'Content Source', description: 'Chooses whether to show an item list or a PDF/image menu.', notes: 'Available choices are Item List and PDF / Image.' },
      { label: 'Layout', description: 'Changes how menu items are arranged.', notes: 'Available layouts include Classic List, Item Grid, Detail Cards, and Compact / Dense.' },
      { label: 'Preview menu', description: 'Lets you preview a specific menu section while editing.', notes: 'This helps with design and does not necessarily change the public default.' },
      { label: 'Show prices', description: 'Shows or hides item prices.' },
      { label: 'Show descriptions', description: 'Shows or hides item descriptions.' },
      { label: 'Show menu tabs', description: 'Shows or hides menu section tabs.' },
      { label: 'Show featured item photos', description: 'Shows or hides photos for featured items.' },
      { label: 'Show regular item photos', description: 'Shows or hides photos for regular items.' },
      { label: 'Show menu item icons', description: 'Shows or hides dietary or custom item icons.' },
      { label: 'Menu Icons', description: 'Controls icons such as Gluten-free, Vegetarian, Vegan, Spicy, and custom icons.' },
      { label: 'Show icon legend', description: 'Shows or hides a legend that explains menu icons.' },
      { label: 'Legend position', description: 'Places the legend above or below the menu.' },
      { label: 'Legend icons', description: 'Controls which icons appear in the legend.', notes: 'Available choices include all icons, only icons used by visible items, or a custom selection.' },
      { label: 'Item Detail Popup', description: 'Turns the click-to-expand item detail popup on or off.' },
      { label: 'Image fit', description: 'Controls how popup photos are displayed.', notes: 'Available options include Fit Full Image, Fill Frame, Centered, and Stretched.' },
      { label: 'Popup photo behavior', description: 'Controls when photos appear in the popup.', notes: 'Photos can always show, or only show when the item photo is already visible in the menu.' },
      { label: 'Popup components', description: 'Shows or hides popup parts.', notes: 'Available parts include full-size photo, item name, description, price, category, and menu icons.' },
      { label: 'Caption background', description: 'Sets the popup caption background color.' },
      { label: 'Caption text color', description: 'Sets the popup caption text color.' },
      { label: 'Category Style', description: 'Changes how categories appear.', notes: 'Available styles include Heading, Badge, and Divider.' },
      { label: 'Section background color', description: 'Sets the menu section background.' },
      { label: 'Reset', description: 'Restores the related menu design setting to its default or previous reset behavior.' },
      { label: 'Custom CSS', description: 'Adds advanced custom styling when available for the account.' },
      { label: 'Manage Items', description: 'Opens the menu management area for adding, editing, reordering, and deleting menus, categories, and items.' },
    ],
    tips: [
      'Use the structured item list when you want tabs, prices, descriptions, photos, icons, and popups.',
      'Use the PDF/image option when you already have a designed menu file.',
      'Keep category names short so tabs stay readable.',
      'Use the legend only when icons add helpful meaning for visitors.',
    ],
    notes: [
      'Menu items are managed separately from visual menu design.',
      'Blank menus and menu categories can be managed from the menu manager.',
    ],
  },
  {
    name: 'Delivery App Links',
    group: 'Commerce and Scheduling',
    summary: 'Adds buttons that link visitors to delivery or ordering services.',
    bestUsedFor: [
      'Restaurant ordering sections',
      'Takeout and delivery pages',
      'Promoting external ordering links',
    ],
    features: [
      'Add a title and subtitle.',
      'Add links for supported delivery platforms or custom ordering links.',
      'Enable or disable individual links.',
      'Preview enabled cards in edit mode even before a URL is entered.',
      'Choose a section background color.',
    ],
    settings: [
      { label: 'Title', description: 'Sets the heading for the delivery links.' },
      { label: 'Subtitle', description: 'Adds supporting text.' },
      { label: 'Background color', description: 'Sets the section background.' },
      { label: 'Delivery links', description: 'Controls the ordering links shown to visitors.', notes: 'Supported choices include Uber Eats, DoorDash, Skip the Dishes, and custom links.' },
      { label: 'Enabled', description: 'Shows or hides an individual ordering link.' },
      { label: 'URL', description: 'Sets the destination for an ordering card.', notes: 'In edit mode, an enabled card without a URL still appears with a warning so the missing link can be fixed before publishing.' },
    ],
    tips: [
      'Test every ordering link before publishing.',
      'Only enable services that are currently available.',
      'Use a custom link for your own ordering page when needed.',
    ],
  },
  {
    name: 'Events',
    group: 'Content Feeds',
    summary: 'Displays upcoming or recent events.',
    bestUsedFor: [
      'Event pages',
      'Community calendars',
      'Promoting upcoming activities',
    ],
    features: [
      'Add a title and subtitle.',
      'Show event cards managed separately.',
      'Sort events by closest first or newest first.',
      'Show or hide past events.',
      'Open the event manager from the block.',
    ],
    settings: [
      { label: 'Title', description: 'Sets the events section heading.' },
      { label: 'Subtitle', description: 'Adds supporting text above the events.' },
      { label: 'Closest first', description: 'Sorts events by the soonest date.' },
      { label: 'Newest first', description: 'Sorts events by the latest date.' },
      { label: 'Showing past events / Hiding past events', description: 'Controls whether past events are included.' },
      { label: 'Manage Events', description: 'Opens the event management area.' },
    ],
    tips: [
      'Use Closest first for upcoming event pages.',
      'Use Newest first when showing announcements or recent activity.',
      'Check that event dates and images are ready before publishing.',
    ],
    notes: [
      'Events are managed separately from the page builder.',
    ],
  },
  {
    name: 'PDF Viewer',
    group: 'Media',
    summary: 'Embeds a PDF document on the page.',
    bestUsedFor: [
      'Menus, brochures, and guides',
      'Downloadable documents',
      'Policy or information sheets',
    ],
    features: [
      'Upload a PDF.',
      'Replace or remove the PDF while editing.',
      'Show the document in an embedded viewer.',
      'Optionally show a download button.',
    ],
    settings: [
      { label: 'Section title', description: 'Sets an optional heading above the PDF.' },
      { label: 'Upload PDF', description: 'Adds the PDF document to the block.', notes: 'The upload area shows a file size limit.' },
      { label: 'Replace PDF', description: 'Swaps the current document for another PDF.' },
      { label: 'Remove', description: 'Removes the current PDF from the block.' },
      { label: 'Show download button', description: 'Shows or hides the download button.' },
      { label: 'Button label', description: 'Sets the text shown on the download button.' },
    ],
    tips: [
      'Use clear document titles so visitors know what they are viewing.',
      'Keep PDFs optimized for web viewing when possible.',
      'Show the download button when visitors may need to save the document.',
    ],
  },
  {
    name: 'Resources',
    group: 'Content Lists',
    summary: 'Shows downloadable files, text resources, and external links.',
    bestUsedFor: [
      'Resource libraries',
      'Guides and forms',
      'Helpful links and reference material',
    ],
    features: [
      'Add a title and subtitle.',
      'Choose Card Grid or Document List layout.',
      'Add file, text, or link resources.',
      'Upload resource files.',
      'Open text resources in an expanded view.',
      'Open external links in a new tab when enabled.',
    ],
    settings: [
      { label: 'Title', description: 'Sets the resources section heading.' },
      { label: 'Subtitle', description: 'Adds supporting text.' },
      { label: 'Card Grid / Document List', description: 'Changes how resources are displayed.' },
      { label: 'Resource title', description: 'Sets the title of an individual resource.' },
      { label: 'Short description', description: 'Adds a brief explanation for a resource.' },
      { label: 'Resource type', description: 'Chooses whether a resource is a file, text item, or link.' },
      { label: 'Upload file', description: 'Adds a downloadable file resource.' },
      { label: 'Resource body text', description: 'Adds the main content for a text resource.' },
      { label: 'URL', description: 'Sets the destination for a link resource.' },
      { label: 'Open in new tab', description: 'Controls whether a link opens in a separate browser tab.' },
      { label: 'Add Resource', description: 'Adds another resource item.' },
    ],
    tips: [
      'Use the Document List layout for practical downloads.',
      'Use Card Grid for a more visual resource library.',
      'Keep resource descriptions short and action-focused.',
    ],
  },
  {
    name: 'Custom HTML / Embed',
    group: 'Advanced',
    plan: 'Pro',
    summary: 'Adds approved custom embed or markup content for advanced use cases.',
    bestUsedFor: [
      'Third-party embed snippets',
      'Special content that does not fit another block',
      'Advanced custom sections handled by someone comfortable with embeds',
    ],
    features: [
      'Paste custom embed or markup content.',
      'Use custom styling inside the block when supported.',
      'Provides a fallback for content that no standard block covers.',
    ],
    settings: [
      { label: 'Custom content', description: 'Controls the custom embed or markup shown in the block.' },
      { label: 'Custom styling', description: 'Adds styling when supported by the account.' },
    ],
    tips: [
      'Use a standard block whenever one can do the job.',
      'Only paste embed content from sources you trust.',
      'Preview the page carefully after changing custom content.',
    ],
    notes: [
      'This block is intended for advanced use.',
      'Some types of embedded behavior may not be supported.',
    ],
  },
  {
    name: 'Featured Quote',
    group: 'Trust',
    summary: 'Highlights a quote, testimonial, or spotlight statement.',
    bestUsedFor: [
      'Prominent testimonials',
      'Founder or customer quotes',
      'Editorial quote sections',
    ],
    features: [
      'Add a quote, person name, and person title.',
      'Use a single-person or multi-person layout.',
      'Choose several quote presentation styles.',
      'Control image position for supported layouts.',
    ],
    settings: [
      { label: 'Quote', description: 'Sets the main quoted text.' },
      { label: 'Person name', description: 'Sets the name attached to the quote.' },
      { label: 'Person title', description: 'Adds a role or short descriptor.' },
      { label: 'Image', description: 'Adds a photo when the selected layout supports it.' },
      { label: 'Image position', description: 'Places the image on the left or right for supported layouts.' },
      { label: 'People', description: 'Adds multiple quote entries for the multi-person layout.' },
      { label: 'Layout', description: 'Changes the quote style.', notes: 'Available layouts include Centered, Split, Minimal / Pull Quote, Essay / Longform, and Multi-Person Grid.' },
    ],
    tips: [
      'Use this block when one quote deserves more emphasis than a standard testimonial card.',
      'Keep the quote readable and avoid very long paragraphs unless using the longform layout.',
      'Use a clear name and role when available.',
    ],
  },
  {
    name: 'Content Carousel',
    group: 'Content Lists',
    summary: 'Displays multiple pieces of content in a carousel-style section.',
    bestUsedFor: [
      'Feature highlights',
      'Step-by-step content',
      'Collections of short visual cards',
    ],
    features: [
      'Add a title and subtitle.',
      'Add repeated carousel items.',
      'Each item can use an image or icon with title and text.',
      'Choose from multiple carousel layouts.',
      'Enable or disable auto-scroll for slide-style layouts.',
    ],
    settings: [
      { label: 'Title', description: 'Sets the carousel section heading.' },
      { label: 'Subtitle', description: 'Adds supporting text.' },
      { label: 'Carousel items', description: 'Controls each card or slide.' },
      { label: 'Media', description: 'Chooses the image or icon used for an item.' },
      { label: 'Item title', description: 'Sets the title for an item.' },
      { label: 'Item text', description: 'Adds supporting text for an item.' },
      { label: 'Layout', description: 'Changes the carousel style.', notes: 'Available layouts include Cards, Split Slides, and Minimal.' },
      { label: 'Auto-scroll slides', description: 'Automatically advances carousel slides when enabled.' },
      { label: 'Interval', description: 'Controls how long each carousel slide stays visible before advancing.' },
    ],
    tips: [
      'Use similar-length text for each item.',
      'Put the most important item first.',
      'Use images or icons consistently across items.',
    ],
  },
  {
    name: 'Video Embed',
    group: 'Media',
    summary: 'Adds a video to the page.',
    bestUsedFor: [
      'Product or service videos',
      'Introductions',
      'Embedded public videos',
    ],
    features: [
      'Paste a video URL.',
      'Supports common video sources shown by the builder.',
      'Add an optional title and caption.',
      'Choose between contained and full-width layouts.',
    ],
    settings: [
      { label: 'Video URL', description: 'Sets the video shown in the block.', notes: 'The editor prompts for YouTube, Vimeo, or a direct video link.' },
      { label: 'Section title', description: 'Sets an optional title above the video.' },
      { label: 'Caption', description: 'Adds optional text below the video.' },
      { label: 'Layout', description: 'Changes the video presentation.', notes: 'Available layouts include Contained and Full Width.' },
    ],
    tips: [
      'Use a clear title when the video needs context.',
      'Add a caption for extra explanation or attribution.',
      'Preview the page after pasting a new video link.',
    ],
  },
  {
    name: 'Social Media Embeds',
    group: 'Media',
    summary: 'Embeds social posts, videos, or timelines.',
    bestUsedFor: [
      'Social proof sections',
      'Recent social content',
      'Embedding public posts from supported platforms',
    ],
    features: [
      'Add an optional section title and subtitle.',
      'Add multiple social URLs.',
      'Automatically detects supported platforms from the URL.',
      'Choose grid or single embed layout.',
      'Choose the number of desktop columns for grid layout.',
    ],
    settings: [
      { label: 'Section title', description: 'Sets an optional heading above the embeds.' },
      { label: 'Subtitle', description: 'Adds optional supporting text.' },
      { label: 'Social URL', description: 'Adds a public social post, video, or page URL.', notes: 'The editor mentions YouTube, Instagram, TikTok, X, and Facebook URLs.' },
      { label: 'Add first embed', description: 'Adds the first social embed.' },
      { label: 'Add another', description: 'Adds another social embed.' },
      { label: 'Layout', description: 'Changes whether embeds appear as a grid or a single centered embed.' },
      { label: 'Columns', description: 'Controls the number of grid columns.', notes: 'Available column counts are 1, 2, 3, and 4.' },
    ],
    tips: [
      'Use public URLs that visitors can access.',
      'Use Single layout for one important post or video.',
      'Keep the number of embeds modest so the page remains easy to browse.',
    ],
    notes: [
      'Unsupported URLs may appear as a link instead of a full embed.',
    ],
  },
  {
    name: 'Tab Bar / Menu Bar',
    group: 'Navigation',
    summary: 'Adds a horizontal tab-style navigation bar.',
    bestUsedFor: [
      'Jump links within a page',
      'Links to important pages',
      'Small menu bars inside a page layout',
    ],
    features: [
      'Add, edit, remove, and reorder tabs.',
      'Link tabs to pages, sections, or custom destinations.',
      'Choose tab style and alignment.',
      'Set active tab color and bar background color.',
      'Use theme colors for tab styling.',
    ],
    settings: [
      { label: 'Add tab', description: 'Adds a new tab to the bar.' },
      { label: 'Edit', description: 'Edits a tab label and destination.' },
      { label: 'Remove', description: 'Removes a tab.' },
      { label: 'Style', description: 'Changes the tab appearance.', notes: 'Available styles include underline, pills, tabs, and buttons.' },
      { label: 'Align', description: 'Changes tab alignment.', notes: 'Available alignments include left, center, right, and stretch.' },
      { label: 'Color', description: 'Sets the active tab color.' },
      { label: 'Bar BG', description: 'Sets or clears the tab bar background.' },
    ],
    tips: [
      'Use short tab labels.',
      'Use Stretch only when the tabs should fill the full width evenly.',
      'Check tab links after changing page or section names.',
    ],
  },
  {
    name: 'User Profile',
    group: 'Membership',
    plan: 'Pro',
    summary: 'Shows profile information for the signed-in member.',
    bestUsedFor: [
      'Member account pages',
      'Membership portals',
      'Private areas for signed-in users',
    ],
    features: [
      'Displays member name, email, and membership details when available.',
      'Allows signed-in members to edit their name.',
      'Includes password change controls.',
      'Can show custom signup information when available.',
    ],
    settings: [
      { label: 'User Profile block', description: 'Displays the signed-in member’s information.' },
      { label: 'Edit name', description: 'Allows the member to update their displayed name.' },
      { label: 'Change password', description: 'Allows the member to change their password.' },
      { label: 'Custom fields', description: 'Shows additional member information when available.' },
    ],
    tips: [
      'Place this block in a member-focused area.',
      'Pair it with a Membership Gate when the page should only be visible to members.',
    ],
    notes: [
      'The block does not show profile information to visitors who are not signed in.',
    ],
  },
  {
    name: 'Membership Gate',
    group: 'Membership',
    plan: 'Pro',
    summary: 'Restricts selected page content to signed-in members.',
    bestUsedFor: [
      'Private member content',
      'Membership-only pages',
      'Content limited to specific membership packages',
    ],
    features: [
      'Adds protected content inside the gate.',
      'Shows a sign-in or upgrade prompt to visitors who do not have access.',
      'Can restrict access to all signed-in members or selected packages.',
      'Allows adding other blocks inside the protected area.',
    ],
    settings: [
      { label: 'Gate Title', description: 'Sets the heading shown when visitors need access.' },
      { label: 'CTA Button Label', description: 'Sets the button text shown on the access prompt.' },
      { label: 'Gate Message', description: 'Sets the explanatory message shown on the access prompt.' },
      { label: 'Restrict to specific packages', description: 'Limits access to selected membership packages.' },
      { label: 'All signed-in members', description: 'Allows any signed-in member to view the protected content.' },
      { label: 'Add block inside gate', description: 'Adds regular builder blocks inside the protected area.' },
    ],
    tips: [
      'Use clear wording so visitors know why content is locked.',
      'Select package restrictions only when content should be available to certain member levels.',
      'Preview the page as a signed-out visitor and as a member when possible.',
    ],
    notes: [
      'Membership packages must be set up before package-specific restrictions are useful.',
    ],
  },
];

export const blockGroups = Array.from(new Set(blockDocs.map((doc) => doc.group)));
