export const PRESET_TEMPLATE_DISPLAYS = {
  atlas: {
    name: 'Utility',
    siteTitle: 'Utility',
    tagline: 'Compact. Structured. Data-ready.',
    description: 'A dense, dashboard-like template for stats, services, pricing, and repeatable process sections.',
    bestFor: ['Stats', 'Process', 'B2B', 'Operations'],
    accent: '#2f6f73',
    badge: 'bg-teal-100 text-teal-800',
  },
  editorial: {
    name: 'Editorial Rule',
    siteTitle: 'Editorial Rule',
    tagline: 'Rule-led. Authoritative. Paper-like.',
    description: 'A publication-style template built around strong rules, compact content cards, and authored sections.',
    bestFor: ['Articles', 'Experts', 'Resources', 'Notes'],
    accent: '#b91c1c',
    badge: 'bg-red-100 text-red-800',
  },
  booked: {
    name: 'Raised',
    siteTitle: 'Raised',
    tagline: 'Elevated. Soft. Appointment-ready.',
    description: 'A premium card-forward template with generous radius, soft depth, and clear booking paths.',
    bestFor: ['Services', 'Booking', 'Pricing', 'Testimonials'],
    accent: '#0f9f8f',
    badge: 'bg-emerald-100 text-emerald-800',
  },
  menu: {
    name: 'Poster',
    siteTitle: 'Poster',
    tagline: 'Image-led. Edge-to-edge. Direct.',
    description: 'A visual template for image-first cards, menu highlights, gallery moments, and direct calls to action.',
    bestFor: ['Food', 'Gallery', 'Menus', 'Features'],
    accent: '#d97706',
    badge: 'bg-orange-100 text-orange-800',
  },
  craft: {
    name: 'Showcase',
    siteTitle: 'Showcase',
    tagline: 'Media-forward. Warm. Story-rich.',
    description: 'A product and story template with framed media, maker proof, and spacious showcase cards.',
    bestFor: ['Products', 'Stories', 'Makers', 'Proof'],
    accent: '#c46a3a',
    badge: 'bg-amber-100 text-amber-800',
  },
  retro: {
    name: 'Retro',
    siteTitle: 'Retro',
    tagline: 'Throwback. Punchy. Shadowed.',
    description: 'A high-personality template with bold borders, hard color shadows, chunky sections, and loud CTAs.',
    bestFor: ['Launches', 'Events', 'Drops', 'Creators'],
    accent: '#ff4fd8',
    badge: 'bg-pink-100 text-pink-800',
  },
  proof: {
    name: 'Ledger',
    siteTitle: 'Ledger',
    tagline: 'Documented. Trust-heavy. Rail-led.',
    description: 'A credibility template with document-like cards, proof sections, testimonials, and intake flows.',
    bestFor: ['Trust', 'Reviews', 'Intake', 'Services'],
    accent: '#15803d',
    badge: 'bg-green-100 text-green-800',
  },
  gallery: {
    name: 'Clipped',
    siteTitle: 'Clipped',
    tagline: 'Angular. Visual. Portfolio-ready.',
    description: 'A crisp visual template with clipped corners, image-led cards, project sections, and minimal chrome.',
    bestFor: ['Portfolio', 'Projects', 'Images', 'Studios'],
    accent: '#111111',
    badge: 'bg-zinc-100 text-zinc-800',
  },
  builder: {
    name: 'Bordered',
    siteTitle: 'Bordered',
    tagline: 'Crisp. Practical. Service-ready.',
    description: 'A clear service template with structured borders, estimate paths, stats, and practical proof blocks.',
    bestFor: ['Services', 'Estimates', 'Trades', 'Proof'],
    accent: '#f59e0b',
    badge: 'bg-amber-100 text-amber-800',
  },
  commerce: {
    name: 'Gradient Wash',
    siteTitle: 'Gradient Wash',
    tagline: 'Color-washed. Product-led. Conversion-ready.',
    description: 'A commerce template with gradient surfaces, product sections, offer cards, and visual feature blocks.',
    bestFor: ['Products', 'Offers', 'Shops', 'Catalogs'],
    accent: '#2563eb',
    badge: 'bg-blue-100 text-blue-800',
  },
  foundation: {
    name: 'Inset',
    siteTitle: 'Inset',
    tagline: 'Pressed-in. Warm. Grounded.',
    description: 'A calm impact template with inset surfaces, community sections, resources, and readable proof cards.',
    bestFor: ['Impact', 'Resources', 'Community', 'Mission'],
    accent: '#0f766e',
    badge: 'bg-teal-100 text-teal-800',
  },
  wellness: {
    name: 'Soft',
    siteTitle: 'Soft',
    tagline: 'Pillowed. Gentle. Reassuring.',
    description: 'A relaxed service template with soft cards, gentle spacing, care content, and testimonial sections.',
    bestFor: ['Care', 'Wellness', 'Services', 'Testimonials'],
    accent: '#16a34a',
    badge: 'bg-green-100 text-green-800',
  },
  estate: {
    name: 'Luxe Hairline',
    siteTitle: 'Luxe Hairline',
    tagline: 'Refined. Visual. Premium.',
    description: 'A premium visual template with fine rules, restrained depth, property-style cards, and gallery flow.',
    bestFor: ['Premium', 'Property', 'Gallery', 'Interiors'],
    accent: '#a16207',
    badge: 'bg-stone-100 text-stone-800',
  },
  studio: {
    name: 'Outline',
    siteTitle: 'Outline',
    tagline: 'Dashed. Modular. Precise.',
    description: 'A creative services template with dashed outlines, modular sections, clipped media, and minimal shadows.',
    bestFor: ['Studios', 'Services', 'Projects', 'Creative'],
    accent: '#db2777',
    badge: 'bg-pink-100 text-pink-800',
  },
  learn: {
    name: 'Accent Rail',
    siteTitle: 'Accent Rail',
    tagline: 'Guided. Compact. Learning-ready.',
    description: 'A structured education template with accent rails, modules, pricing, resources, and clear next steps.',
    bestFor: ['Courses', 'Modules', 'Pricing', 'Resources'],
    accent: '#2563eb',
    badge: 'bg-indigo-100 text-indigo-800',
  },
  occasion: {
    name: 'Playful',
    siteTitle: 'Playful',
    tagline: 'Chunky. Lifted. Celebratory.',
    description: 'A lively template with playful cards, event-ready sections, glow accents, and celebratory calls to action.',
    bestFor: ['Events', 'Venues', 'Celebrations', 'Inquiries'],
    accent: '#ec4899',
    badge: 'bg-rose-100 text-rose-800',
  },
} as const;

export type PresetTemplateStyle = keyof typeof PRESET_TEMPLATE_DISPLAYS;

export function getPresetTemplateDisplay(style: string | null | undefined) {
  const normalized = (style || '').toLowerCase().replace(/-/g, '_');
  return PRESET_TEMPLATE_DISPLAYS[normalized as PresetTemplateStyle];
}
